title: The Kendric Blog
email: ngkendric@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog

url: https://www.kendric.blog
twitter_username: kendricng
github_username:  kenterminator

disqus:
  shortname: 'kendric-blog'
mailchimp:
  url: https://societypieces.us16.list-manage.com/subscribe/post?u=bab6ad2e6b37baee2ac6487ba&amp;id=527733b981
  hidden: b_bab6ad2e6b37baee2ac6487ba_527733b981

font-url: 'https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700'

# Build settings
markdown: kramdown
timezone: Asia/Hong_Kong
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib', 'vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
author: Kendric Ng
plugins:
  - jekyll-feed
sass:
  style: compressed

# social profiles
social:
  - profile: facebook
    url: ''
    icon: 'fab fa-facebook-f'
  - profile: twitter
    url: ''
    icon: 'fab fa-twitter'
  - profile: instagram
    url: ''
    icon: 'fab fa-instagram'